# FBI NIBRS Dataset

#### The clean_nibrs_df function in this notebook should be able to do the preliminary data cleaning on all of the Federal NIBRS datasets found here [https://ucr.fbi.gov/nibrs/2018/tables/data-tables#federal-table](https://ucr.fbi.gov/nibrs/2018/tables/data-tables#federal-table). Simply change the year in the URL to get the corresponding table.

In [13]:
import pandas as pd

In [14]:
# Load 2019 FBI NIBRS data

df_nibrs_19 = pd.read_excel('data/United_States_Offense_Type_by_Agency_2019.xls', skiprows=[0,1,2])

df_nibrs_19.head(25)

,State,Agency Type,Agency Name,Population1,Total\nOffenses,Crimes\nAgainst\nPersons,Crimes\nAgainst\nProperty,Crimes\nAgainst\nSociety,Crimes Against Persons,Unnamed: 9,...,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assault\nOffenses,Aggravated\nAssault,...,Betting/\nWagering,Operating/\nPromoting/\nAssisting\nGambling,Gambling\nEquipment\nViolations,Sports\nTampering,Por-\nnography/\nObscene\nMaterial,Pros-\ntitution\nOffenses,Pros-\ntitution,Assisting or\nPromoting\nProstitution,Purchasing\nProstitution,Weapon\nLaw\nViolations
1,ALABAMA,Cities,Hoover,85670.0,4293.0,840.0,2801.0,652.0,811,68,...,0,0,0,0,2,1,1,0,0,67
2,ARIZONA,Cities,Apache Junction2,42531.0,NaN,430.0,NaN,487.0,383,71,...,0,0,0,0,6,0,0,0,0,36
3,NaN,NaN,Coolidge,13138.0,1155.0,230.0,684.0,241.0,214,61,...,0,0,0,0,1,0,0,0,0,18
4,NaN,NaN,Eagar,4897.0,102.0,36.0,29.0,37.0,21,7,...,0,0,0,0,0,0,0,0,0,1
5,NaN,NaN,Gilbert,253619.0,10589.0,1844.0,6144.0,2601.0,1642,157,...,0,0,0,0,47,10,10,0,0,78
6,NaN,NaN,Huachuca City,1723.0,73.0,26.0,41.0,6.0,20,1,...,0,0,0,0,0,0,0,0,0,0
7,NaN,NaN,Somerton,16771.0,257.0,70.0,155.0,32.0,57,15,...,0,0,0,0,1,0,0,0,0,5
8,NaN,NaN,Wellton,3048.0,105.0,26.0,58.0,21.0,24,4,...,0,0,0,0,0,0,0,0,0,1
9,NaN,NaN,Yuma,98769.0,7037.0,1110.0,4575.0,1352.0,965,309,...,0,0,0,0,30,2,0,2,0,93
10,NaN,Metropolitan Counties,Yuma,NaN,2987.0,742.0,1862.0,383.0,688,109,...,0,0,0,0,7,0,0,0,0,35
11,ARKANSAS,Cities,Alexander,3315.0,216.0,55.0,113.0,48.0,48,9,...,0,0,0,0,0,0,0,0,0,1
12,NaN,NaN,Alma,5888.0,616.0,213.0,341.0,62.0,189,15,...,0,0,0,0,0,0,0,0,0,2
13,NaN,NaN,Altus,729.0,63.0,11.0,30.0,22.0,11,0,...,0,0,0,0,0,0,0,0,0,0
14,NaN,NaN,Amity,675.0,14.0,7.0,3.0,4.0,7,1,...,0,0,0,0,0,0,0,0,0,1
15,NaN,NaN,Ashdown,4370.0,322.0,65.0,156.0,101.0,60,10,...,0,0,0,0,0,0,0,0,0,2
16,NaN,NaN,Ash Flat,1095.0,86.0,19.0,52.0,15.0,19,5,...,0,0,0,0,0,0,0,0,0,0
17,NaN,NaN,Atkins,3037.0,223.0,50.0,116.0,57.0,44,5,...,0,0,0,0,0,0,0,0,0,2
18,NaN,NaN,Augusta,1939.0,119.0,38.0,69.0,12.0,31,7,...,0,0,0,0,0,0,0,0,0,2
19,NaN,NaN,Austin,3973.0,102.0,13.0,42.0,47.0,13,4,...,0,0,0,0,0,0,0,0,0,4
20,NaN,NaN,Bald Knob,2872.0,405.0,136.0,193.0,76.0,127,12,...,0,0,0,0,1,2,2,0,0,3
21,NaN,NaN,Barling,5010.0,561.0,128.0,126.0,307.0,115,19,...,0,0,0,0,1,0,0,0,0,12
22,NaN,NaN,Batesville,10889.0,678.0,79.0,380.0,219.0,73,22,...,0,0,0,0,0,0,0,0,0,14
23,NaN,NaN,Bay,1805.0,70.0,20.0,33.0,17.0,17,2,...,0,0,0,0,0,0,0,0,0,2
24,NaN,NaN,Bearden,859.0,12.0,3.0,9.0,0.0,3,1,...,0,0,0,0,0,0,0,0,0,0

In [15]:
def clean_nibrs_df(df, year):

    # Get missing column names
    names = df.iloc[0].tolist()
    missing_names = names[8:]
    # missing_names = [name.replace('\n', ' ').replace(' ', '_').replace('/_', '/').replace('-_', '').replace('__', '_') for name in missing_names]

    #Get column names and replace UnNamed columns with the corresponding name
    column_names = df.columns.to_list()
    column_names = column_names[:8]
    for name in missing_names:
        column_names.append(name)

    #Clean the column names up
    column_names = [name.replace('\n', ' ').replace(' ', '_').replace('/_', '/').replace('-_', '').replace('__', '_') for name in column_names]
    df.columns = column_names
    df = df.drop(df.index[0])
    
    # Replace NaN values in 'State' with the first non-NaN value using ffill
    df['State'] = df['State'].fillna(method='ffill')

    # Replace NaN values in 'Agency_Type' with the first non-NaN value using ffill
    df['Agency_Type'] = df['Agency_Type'].fillna(method='ffill')
    
    #filter to the city level
    df = df[df["Agency_Type"]=="Cities"]
    
    df["Year"] = year
    
    return df

In [16]:
cleaned_df_nibrs_19 = clean_nibrs_df(df_nibrs_19, 2019)

cleaned_df_nibrs_19.head(20)

,State,Agency_Type,Agency_Name,Population1,Total_Offenses,Crimes_Against_Persons,Crimes_Against_Property,Crimes_Against_Society,Assault_Offenses,Aggravated_Assault,...,Operating/Promoting/Assisting_Gambling,Gambling_Equipment_Violations,Sports_Tampering,Pornography/Obscene_Material,Prostitution_Offenses,Prostitution,Assisting_or_Promoting_Prostitution,Purchasing_Prostitution,Weapon_Law_Violations,Year
1,ALABAMA,Cities,Hoover,85670.0,4293.0,840.0,2801.0,652.0,811,68,...,0,0,0,2,1,1,0,0,67,2019
2,ARIZONA,Cities,Apache Junction2,42531.0,NaN,430.0,NaN,487.0,383,71,...,0,0,0,6,0,0,0,0,36,2019
3,ARIZONA,Cities,Coolidge,13138.0,1155.0,230.0,684.0,241.0,214,61,...,0,0,0,1,0,0,0,0,18,2019
4,ARIZONA,Cities,Eagar,4897.0,102.0,36.0,29.0,37.0,21,7,...,0,0,0,0,0,0,0,0,1,2019
5,ARIZONA,Cities,Gilbert,253619.0,10589.0,1844.0,6144.0,2601.0,1642,157,...,0,0,0,47,10,10,0,0,78,2019
6,ARIZONA,Cities,Huachuca City,1723.0,73.0,26.0,41.0,6.0,20,1,...,0,0,0,0,0,0,0,0,0,2019
7,ARIZONA,Cities,Somerton,16771.0,257.0,70.0,155.0,32.0,57,15,...,0,0,0,1,0,0,0,0,5,2019
8,ARIZONA,Cities,Wellton,3048.0,105.0,26.0,58.0,21.0,24,4,...,0,0,0,0,0,0,0,0,1,2019
9,ARIZONA,Cities,Yuma,98769.0,7037.0,1110.0,4575.0,1352.0,965,309,...,0,0,0,30,2,0,2,0,93,2019
11,ARKANSAS,Cities,Alexander,3315.0,216.0,55.0,113.0,48.0,48,9,...,0,0,0,0,0,0,0,0,1,2019
12,ARKANSAS,Cities,Alma,5888.0,616.0,213.0,341.0,62.0,189,15,...,0,0,0,0,0,0,0,0,2,2019
13,ARKANSAS,Cities,Altus,729.0,63.0,11.0,30.0,22.0,11,0,...,0,0,0,0,0,0,0,0,0,2019
14,ARKANSAS,Cities,Amity,675.0,14.0,7.0,3.0,4.0,7,1,...,0,0,0,0,0,0,0,0,1,2019
15,ARKANSAS,Cities,Ashdown,4370.0,322.0,65.0,156.0,101.0,60,10,...,0,0,0,0,0,0,0,0,2,2019
16,ARKANSAS,Cities,Ash Flat,1095.0,86.0,19.0,52.0,15.0,19,5,...,0,0,0,0,0,0,0,0,0,2019
17,ARKANSAS,Cities,Atkins,3037.0,223.0,50.0,116.0,57.0,44,5,...,0,0,0,0,0,0,0,0,2,2019
18,ARKANSAS,Cities,Augusta,1939.0,119.0,38.0,69.0,12.0,31,7,...,0,0,0,0,0,0,0,0,2,2019
19,ARKANSAS,Cities,Austin,3973.0,102.0,13.0,42.0,47.0,13,4,...,0,0,0,0,0,0,0,0,4,2019
20,ARKANSAS,Cities,Bald Knob,2872.0,405.0,136.0,193.0,76.0,127,12,...,0,0,0,1,2,2,0,0,3,2019
21,ARKANSAS,Cities,Barling,5010.0,561.0,128.0,126.0,307.0,115,19,...,0,0,0,1,0,0,0,0,12,2019

In [17]:
print(cleaned_df_nibrs_19.shape)
cleaned_df_nibrs_19.info()

(4168, 70)
<class 'pandas.core.frame.DataFrame'>
Index: 4168 entries, 1 to 6582
Data columns (total 70 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   State                                        4168 non-null   object
 1   Agency_Type                                  4168 non-null   object
 2   Agency_Name                                  4168 non-null   object
 3   Population1                                  4168 non-null   float64
 4   Total_Offenses                               4143 non-null   float64
 5   Crimes_Against_Persons                       4165 non-null   float64
 6   Crimes_Against_Property                      4146 non-null   float64
 7   Crimes_Against_Society                       4168 non-null   float64
 8   Assault_Offenses                             4168 non-null   object
 9   Aggravated_Assault                           4168 non-null   object
 10  Simple_Assault                               4168 non-null   object
 11  Intimidation                                 4168 non-null   object
 12  Homicide_Offenses                            4165 non-null   object
 13  Murder_and_Nonnegligent_Manslaughter         4165 non-null   object
 14  Negligent_Manslaughter                       4168 non-null   object
 15  Justifiable_Homicide                         4168 non-null   object
 16  Human_Trafficking_Offenses                   4168 non-null   object
 17  Commercial_Sex_Acts                          4168 non-null   object
 18  Involuntary_Servitude                        4168 non-null   object
 19  Kidnapping/Abduction                         4168 non-null   object
 20  Sex_Offenses                                 4168 non-null   object
 21  Rape                                         4168 non-null   object
 22  Sodomy                                       4168 non-null   object
 23  Sexual_Assault_With_an_Object                4168 non-null   object
 24  Fondling                                     4168 non-null   object
 25  Incest                                       4168 non-null   object
 26  Statutory_Rape                               4168 non-null   object
 27  Arson                                        4165 non-null   object
 28  Bribery                                      4168 non-null   object
 29  Burglary/Breaking_&_Entering                 4155 non-null   object
 30  Counterfeiting/Forgery                       4168 non-null   object
 31  Destruction/Damage/Vandalism_of_Property     4168 non-null   object
 32  Embezzlement                                 4168 non-null   object
 33  Extortion/Blackmail                          4168 non-null   object
 34  Fraud_Offenses                               4168 non-null   object
 35  False_Pretenses/Swindle/Confidence_Game      4168 non-null   object
 36  Credit_Card/Automated_Teller_Machine_Fraud   4168 non-null   object
 37  Impersonation                                4168 non-null   object
 38  Welfare_Fraud                                4168 non-null   object
 39  Wire_Fraud                                   4168 non-null   object
 40  Identity_Theft                               4168 non-null   object
 41  Hacking/Computer_Invasion                    4168 non-null   object
 42  Larceny/Theft_Offenses                       4163 non-null   object
 43  Pocketpicking                                4163 non-null   object
 44  Pursesnatching                               4163 non-null   object
 45  Shoplifting                                  4163 non-null   object
 46  Theft_From_Building                          4163 non-null   object
 47  Theft_From_Coin_Operated_Machine_or_Device   4163 non-null   object
 48  Theft_From_Motor_Vehicle                     4163 non-null   object
 49  Theft_of_Motor_Vehicle_Parts_or_Accessories  4163 non-null   object
 50  All_Other_Larceny                            4163 non-null   object
 51  Motor_Vehicle_Theft                          4168 non-null   object
 52  Robbery                                      4167 non-null   object
 53  Stolen_Property_Offenses                     4168 non-null   object
 54  Animal_Cruelty                               4168 non-null   object
 55  Drug/Narcotic_Offenses                       4168 non-null   object
 56  Drug/Narcotic_Violations                     4168 non-null   object
 57  Drug_Equipment_Violations                    4168 non-null   object
 58  Gambling_Offenses                            4168 non-null   object
 59  Betting/Wagering                             4168 non-null   object
 60  Operating/Promoting/Assisting_Gambling       4168 non-null   object
 61  Gambling_Equipment_Violations                4168 non-null   object
 62  Sports_Tampering                             4168 non-null   object
 63  Pornography/Obscene_Material                 4168 non-null   object
 64  Prostitution_Offenses                        4168 non-null   object
 65  Prostitution                                 4168 non-null   object
 66  Assisting_or_Promoting_Prostitution          4168 non-null   object
 67  Purchasing_Prostitution                      4168 non-null   object
 68  Weapon_Law_Violations                        4168 non-null   object
 69  Year                                         4168 non-null   int64
dtypes: float64(5), int64(1), object(64)
memory usage: 2.3+ MB